import Head from 'next/head'
import router from 'next/router'
import Table from '@mui/material/Table'
import TableHead from '@mui/material/TableHead'
import TableBody from '@mui/material/TableBody'
import TableRow from '@mui/material/TableRow'
import TableCell from '@mui/material/TableCell'
import TableContainer from '@mui/material/TableContainer'
import  Paper   from '@mui/material/Paper'
import Pagination from '@mui/material/Pagination'
import {GetServerSideProps} from 'next'
import { getData } from '../utils/serverSideProps'
import { params } from '../types/severSideTypes'
import {placeType} from '../types/placeType'
import {DataTable} from '../components/dataTable'

export default function Home({ places }: placeType) {

 return (
    <>
      <Head>
        <title>Uk place data</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
     <DataTable places={places} />

    </>
  )
}

export async function getServerSideProps(cxt:GetServerSideProps&params) {
  return getData(cxt)
}

